defaults:
  llama_stack:
    endpoint: "http://localhost:8321"
    api_key: null
    timeout: 60
    model: "meta-llama/Llama-3.2-3B-Instruct"
  model:
    name: "meta-llama/Llama-3.2-3B-Instruct"
    temperature: 0.7
    max_tokens: 2048
  tools:
    approach: "client_tools"
    ansible_lint:
      profile: "basic"
      timeout: 60
  agent:
    instructions: |
      You are an expert Ansible playbook validation agent. Your role is to:
      1. Always use the ansible_lint_tool when asked to validate a playbook
      2. Analyze and explain the lint results for users
      3. Be thorough, clear, and educational in your response
    max_infer_iters: 10
    enable_session_persistence: false
  app:
    name: "x2ansible"
    version: "1.0.0"
    debug: false
    cors_origins: ["*"]
  logging:
    level: "INFO"
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

profiles:
  local:
    llama_stack:
      endpoint: "http://localhost:8321"
      model: "meta-llama/Llama-3.2-3B-Instruct"
    app:
      debug: true
      cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
    logging:
      level: "DEBUG"
  
  remote:
    llama_stack:
      endpoint: "http://lss-chai.apps.cluster-7nc6z.7nc6z.sandbox2170.opentlc.com"
      model: "meta-llama/Llama-3.2-3B-Instruct"
    app:
      debug: false
    logging:
      level: "INFO"
  
  production:
    llama_stack:
      endpoint: "${LLAMASTACK_ENDPOINT}"
      api_key: "${LLAMASTACK_API_KEY}"
      model: "meta-llama/Llama-3.2-3B-Instruct"
    app:
      debug: false
